### ISSUE TITLE
Bug: Environment's `sample` method ignores interventions?

### ISSUE THREAD

**Issue by st--** [chritoth/active-bayesian-causal-inference#1]
Hi, it looks like the `sample` method of the `Environment` base class defined in https://github.com/chritoth/active-bayesian-causal-inference/blob/master/src/environments/environment.py#L128 does not actually use the interventions to affect the ancestral sampling. Is this intentional, or a bug? (If intentional, where does the ancestral sampling with interventions actually happen?)

**Comment by chritoth** [comment]
Hi, thanks for reporting this! You are right, the interventions parameter was unused in the ancestral sampling, with was an error introduced during the refactoring process for the initial code version published here. It's now fixed by commit 4aa8e9b.
